### ISSUE TITLE
Spacy-clausie license

### ISSUE THREAD

**Issue by dmilcevski** [mmxgn/spacy-clausie#15]
Hi,

Thanks for re-writing clausIE into python. I was wondering what is the rational behind the GPL-3 license, when clausIE itself, or the codebase of clausIE is Apache2.0?

Thank you!

**Comment by mmxgn** [comment]
Hi,

This is not a re-write since no code from the original ClausIE has been used but was implemented directly from the paper.

**Comment by mmxgn** [comment]
Hi

Thank you for your suggestion and your interest in Claucy.

I will not be changing however the License to a more permissive one. Again, this is a library I wrote by replicating the paper because I needed at that time, not the code which I've never looked upon (I am very unfamiliar with java). If someone needs to use it with the CC-BY 3.0 License through python, they can try creating their own bindings for Clausie, similar to the one I've done for Minie in MiniePy.

>  Disclaimer, as a former co-founder of Ambiverse, I am very familiar with ClausIE.

I am confused on why you mentioned this. The license as listed on the official site is CC-BY 3.0 and not Apache 2.0. But again, It is irrelevant since no code has been used. If you know of something more, please provide relevant/additional info, preferably in the form of links.

**Comment by mmxgn** [comment]
I am also happy to link to a python alternative by Ambiverse if that becomes available :)

**Comment by dmilcevski** [comment]
Thanks once again. I think we can close the thread. Ambiverse doesn't exist anymore, and the codebase is not maintained.
