### ISSUE TITLE
clause extract question

### ISSUE THREAD

**Issue by lu161513** [mmxgn/spacy-clausie#5]
the blood warmer is a device to warm up the extra corporeal blood before it returns to patient's body.

can we get:
the blood warmer is a device
a device to warm up the extra corporeal blood
before it returns to patient's body.

**Comment by mmxgn** [comment]
Hi,

Thank you for your interest in `claucy`.

Unfortunately `claucy` does not currently support this. The main issue is that apart from the first clause the other two are not full sentences and require some transformation so that it would be similar to:

- The blood warmer is a device.
- The device warms up the extra corporeal blood.
- It returns to patient's body.

I will take a look. I do not currently plan to work on more features for `claucy` since it's served its purpose for me, you are welcome to submit a pull request if you manage to add this functionality, however!
