### ISSUE TITLE
Missing two items from example sentence.

### ISSUE THREAD

**Issue by AdamNix** [mmxgn/spacy-clausie#7]
Great program. Thank you for taking ClausIE and making this practical program. 
I'm having two problems with it.  Both relate to the Aesop example.

**### Problem 1**
Running the program, I get:

['the birds were ailing']
['A cat dressed himself', 'A cat dressed himself as a physician']
['A cat took his cane', 'A cat took a bag']
['A cat became this profession']

I don't know why I am not getting the final two:
['A cat went.']
['A cat called on them.']

The code I'm using is identical to the one in the 'Usage' section.
doc._.clauses is a list that contains four rather than six.

**### Problem 2**
The genius cat has a bag of instruments. 
The program comes back with 'A cat took a bag.'
Why were the instruments dropped?

Best Regards

Adam Nixon

**Comment by mmxgn** [comment]
Hi, thanks for your interest.

Regarding the first part:
Which spacy version are you using?

Regarding the second, I assume you mean "A cat has a bag".

The library is rule-based, that means its ought to miss some cases. I have stopped improving it since it's served its purpose for me, however you are welcome to contribute to its rules and submit a PR.
